version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - pg_store:/var/lib/postgresql/data

volumes:
  pg_store:
